module.exports = {
  SECRET_KEY: "THIS IS SECRET KEY",
  REFRESH_SECRET_KEY: "THIS IS REFRESH SECRET KEY",
  TOKEN_LIFE: 28800,
  REFRESH_TOKEN_LIFE: 28800,
  SALT_ROUNDS: 10,
  TOKEN_FORMAT: "Bearer",
};