module.exports = {
  TOKEN_SECRET: "THIS IS SECRET KEY",
  REFRESH_TOKEN_SECRET: "THIS IS REFRESH SECRET KEY",
  TOKEN_LIFE: 28800,
  REFRESH_TOKEN_LIFE: 1800,
  SALT_ROUNDS: 10,
  TOKEN_TYPE: "Bearer",
};